# Generated by Django 3.1.4 on 2021-01-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_auto_20210106_1736'),
        ('themes', '0001_initial'),
        ('personal_dictionaries', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ManyToManyField(related_name='phrases', to='categories.Category')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='personal_dictionaries.personaldictionary')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='languages.language')),
                ('theme', models.ManyToManyField(related_name='phrases', to='themes.Theme')),
            ],
        ),
        migrations.AddConstraint(
            model_name='phrase',
            constraint=models.UniqueConstraint(fields=('name', 'dictionary', 'language'), name='the phrase name must be unique within the dictionary and language'),
        ),
    ]
