# Generated by Django 3.1.5 on 2021-01-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0002_dictionary_user_profile'),
        ('themes', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='dictionaries.dictionary')),
                ('theme', models.ManyToManyField(related_name='phrases', to='themes.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='PhraseTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_translations', to='languages.language')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_translations', to='phrases.phrase')),
            ],
        ),
        migrations.AddConstraint(
            model_name='phrasetranslation',
            constraint=models.UniqueConstraint(fields=('phrase', 'language'), name='phrase and language must be unique within the dictionary'),
        ),
    ]
