# Generated by Django 3.1.4 on 2021-01-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conjugation_links', '0001_initial'),
        ('personal_dictionaries', '0002_personaldictionary_user_profile'),
        ('themes', '0001_initial'),
        ('categories', '0002_auto_20210106_1736'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Noun'), ('V', 'Verb'), ('A', 'Adjective')], max_length=20)),
                ('category', models.ManyToManyField(related_name='words', to='categories.Category')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='personal_dictionaries.personaldictionary')),
                ('theme', models.ManyToManyField(related_name='words', to='themes.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('conjugation_link', models.ForeignKey(default='https://www.verbformen.ru/sprjazhenie/', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='verbs', to='conjugation_links.conjugationlink')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbs', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singular_name', models.CharField(max_length=50)),
                ('plural_name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noun_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nouns', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('conjugation_link', models.ForeignKey(default='https://www.verbformen.ru/sklonenie/prilagatelnye/', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='adjectives', to='conjugation_links.conjugationlink')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjective_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjective', to='words.word')),
            ],
        ),
        migrations.AddConstraint(
            model_name='verb',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='the verb name must be unique within a language'),
        ),
        migrations.AddConstraint(
            model_name='noun',
            constraint=models.UniqueConstraint(fields=('singular_name', 'plural_name', 'language'), name='the noun singular and plural name must be unique within a language'),
        ),
        migrations.AddConstraint(
            model_name='adjective',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='the adjective name must be unique within a language'),
        ),
    ]
