# Generated by Django 3.1.4 on 2021-01-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_dictionaries', '0002_personaldictionary_user_profile'),
        ('themes', '0001_initial'),
        ('languages', '0001_initial'),
        ('categories', '0002_auto_20210106_1736'),
        ('conjugation_links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Noun'), ('V', 'Verb'), ('A', 'Adjective')], max_length=20)),
                ('category', models.ManyToManyField(related_name='words', to='categories.Category')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='personal_dictionaries.personaldictionary')),
                ('theme', models.ManyToManyField(related_name='words', to='themes.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='RussianVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_verb_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_verbs', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='RussianNoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singular_name', models.CharField(max_length=50)),
                ('plural_name', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_noun_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_nouns', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='RussianAdjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_adjective_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_adjectives', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='GermanVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('conjugation_link', models.ForeignKey(default='https://www.verbformen.ru/sprjazhenie/', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='german_verbs', to='conjugation_links.conjugationlink')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='german_verb_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='german_verbs', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='GermanNoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singular_name', models.CharField(max_length=50)),
                ('plural_name', models.CharField(max_length=50)),
                ('singular_article', models.CharField(choices=[('der', 'der'), ('die', 'die'), ('das', 'das')], max_length=3)),
                ('plural_article', models.CharField(default='die', max_length=3)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='german_noun_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='german_nouns', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='GermanAdjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('conjugation_link', models.ForeignKey(default='https://www.verbformen.ru/sklonenie/prilagatelnye/', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='german_adjectives', to='conjugation_links.conjugationlink')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='german_adjective_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='german_adjectives', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_verb_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_verbs', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishNoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singular_name', models.CharField(max_length=50)),
                ('plural_name', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_noun_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_nouns', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishAdjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_adjective_words', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_adjectives', to='words.word')),
            ],
        ),
        migrations.AddConstraint(
            model_name='russianverb',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='the verb name must be unique within a russian language'),
        ),
        migrations.AddConstraint(
            model_name='russiannoun',
            constraint=models.UniqueConstraint(fields=('plural_name', 'singular_name', 'language'), name='the noun singular and plural name must be unique within a russian language'),
        ),
        migrations.AddConstraint(
            model_name='russianadjective',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='the adjective name must be unique within a russian language'),
        ),
        migrations.AddConstraint(
            model_name='germanverb',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='the verb name must be unique within a german language'),
        ),
        migrations.AddConstraint(
            model_name='germannoun',
            constraint=models.UniqueConstraint(fields=('plural_name', 'singular_name', 'language'), name='the noun singular and plural name must be unique within a german language'),
        ),
        migrations.AddConstraint(
            model_name='germanadjective',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='the adjective name must be unique within a german language'),
        ),
        migrations.AddConstraint(
            model_name='englishverb',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='the verb name must be unique within a english language'),
        ),
        migrations.AddConstraint(
            model_name='englishnoun',
            constraint=models.UniqueConstraint(fields=('plural_name', 'singular_name', 'language'), name='the noun singular and plural name must be unique within a english language'),
        ),
        migrations.AddConstraint(
            model_name='englishadjective',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='the adjective name must be unique within a english language'),
        ),
    ]
