# Generated by Django 3.1.5 on 2021-01-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('languages', '0001_initial'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='dictionaries.dictionary')),
                ('theme', models.ManyToManyField(related_name='words', to='themes.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('N', 'Noun'), ('V', 'Verb'), ('Adj', 'Adjective'), ('Adv', 'Adverb'), ('Num', 'Numeral'), ('Prep', 'Preposition'), ('Pron', 'Pronoun'), ('U', 'Union'), ('Part', 'Particle'), ('Art', 'Article')], max_length=30)),
                ('extra', models.JSONField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_translations', to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_translations', to='words.word')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wordtranslation',
            constraint=models.UniqueConstraint(fields=('word', 'language'), name='word and language must be unique within the dictionary'),
        ),
    ]
