# Generated by Django 3.1.4 on 2021-01-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('personal_dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='personal_dictionaries.personaldictionary'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'dictionary'), name='the category name must be unique within the dictionary'),
        ),
    ]
